### ISSUE TITLE
Test Application and resources shouldn't be bundled/contained

### ISSUE THREAD

**Issue by mweirauch** [BjoernKW/Schematic#12]
IMHO this library should not include the test `SchematicApplication` and its related resources.

This leads to:
* a smell of having a `main()` in a library
* `application.yml` being picked up by the including project
  * leading to immediately having to include the PostgreSQL driver in case you have not yet overridden `spring.datasource.url` in the including project (Spring Datasource auto configuration trying to load the PostgreSQL driver because it derives it from the pre-configured JDBC url)
* `spring.sql.init.mode=always` leading to `schema.sql` and `data.sql` being picked up in an including project
  * this leads to the creation of the `example` table with one example entry, which you really don't to happen in a users schema
  * apart from this, the configured user might not have DDL permissions in the including project

Reproducer:
* create a quick simple project at https://start.spring.io/ and add Schematic as a dependency

While I do understand the convenience during development, the end-user impact might be a bit too much I guess.

**Comment by BjoernKW** [comment]
Thank you very much for your input! I agree this could cause the problems you mentioned for the library user. I've come with this quick solution for preventing those developer support files from ending up in the distribution package:

https://github.com/BjoernKW/Schematic/pull/13

Could you have a look at that pull request and see if in you opinion that solves the issue?

**Comment by mweirauch** [comment]
Hi Björn, yes that solves it on a quick glance. Thank you!
