### ISSUE TITLE
Interest in Spring 2/Java 11 support?

### ISSUE THREAD

**Issue by checketts** [BjoernKW/Schematic#6]
I'm interested in leveraging Schematic in an AWS Lambda environment. However, AWS Lambda doesn't support Java 17 yet. So I need to use Java 11.

If I were to back-port Schematic to run on Java 11 would you be interested in that code?

**Comment by BjoernKW** [comment]
Thanks for getting in touch! Yes, that'd certainly be interesting, especially as so far I haven't considered that particular use case.

**Comment by checketts** [comment]
I've created a boot 2 branch: https://github.com/checketts/Schematic/tree/boot-2

Would you like to create a 'boot-2' branch in this repo for me to PR it into? I changed the artifact name to 'schematic-boot-2' so it can track independently from the main one.

**Comment by checketts** [comment]
Luckily Spring 2.7.2  supports the spring.factories replacement, so the code changes is minimal.

**Comment by BjoernKW** [comment]
Thanks a lot! @checketts Looks good. I've just create a `java-11-spring-boot-2` branch as a target for your pull request.

**Comment by BjoernKW** [comment]
@checketts Fyi, I've just published a dedicated Maven artefact for Spring Boot 2 / Java 11 (should be available at Maven Central soon):

```
<dependency>
    <groupId>com.bjoernkw</groupId>
    <artifactId>schematic</artifactId>
    <version>0.1.8.jre11</version>
</dependency>
```

**Comment by checketts** [comment]
Nice! I'll look into using it this week!
