### ISSUE TITLE
Provide a way to specify path prefix

### ISSUE THREAD

**Issue by bob-tee** [BjoernKW/Schematic#82]
I have an application that is deployed under a sub-directory. Something like:
http://domain.com/somedir

I don't have control of the `somedir` name and my application context path is `"/"`.

All the paths in Schematic reference the root like `/css/styles` . This means for my use-case none of the assets load and Schematic is not usable. It would be great if there was some way to specify the base path or use relative paths so Schematic will work as expected.

**Comment by BjoernKW** [comment]
@bob-tee Thanks for the input. This feature will be available in the next version (`0.3.0`). It's already implemented on the `main` branch now.

**Comment by BjoernKW** [comment]
@bob-tee FYI, I've just create the `0.3.0` release. It should be available on Maven Central in a few hours.
